version: '3'
services:
  db:
    build: db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Europe/Prague'

  php:
    build: php
    volumes:
      - ../src:/var/www/html

volumes:
  db-data:
