version: '3'
services:
  db:
    build: db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Europe/Prague'

  php:
    build: php
    volumes:
      - ../src:/var/www/html
    environment:
      PANTHER_NO_SANDBOX: '1'
      PANTHER_CHROME_ARGUMENTS: '--window-size=1920,1080'
      PANTHER_EXTERNAL_BASE_URI: 'http://docker.me'
    extra_hosts:
      - "docker.me:127.0.0.1"
    shm_size: 256m # prevents WebDriver from crashing in a headless mode

volumes:
  db-data:
