security:
    encoders:
        Symfony\Component\Security\Core\User\User: auto

    providers:
        admin:
            memory:
                users:
                    admin: { password: '$argon2id$v=19$m=65536,t=4,p=1$iP1YKi7YXIWqw3h/nqDtuQ$4MwJ5QqyW4GlnUQO95aEWS19F7yy7yXcPxIWMlfsA9k', roles: ['ROLE_ADMIN'] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            guard:
                authenticators:
                    - App\Security\LoginAuthenticator

            logout:
                path: /admin/logout

    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
